apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting-service
          image: waytodanny/k8s-101-greeting-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  type: NodePort
  selector:
    app: greeting
  ports:
    - protocol: TCP
      #the port number which is exposed by the Kubernetes service. External services, or services within the same cluster, will communicate with this service on this port number.
      port: 8081
      #the port number on the pods where the actual service is running and requests will be sent. It is the port of your application on the actual pods targeted by the service.
      targetPort: 8081
      nodePort: 30001