apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting-service
          image: waytodanny/k8s-101-greeting-service
          ports:
            - containerPort: 8081
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: greeting-environment-variables
                  key: env