apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-ingress
  annotations:
    nginx.org/rewrites: "serviceName=greeting rewrite=/"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: /api/
            backend:
              service:
                name: greeting
                port:
                  number: 8081