apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  # Exposes the Service on a cluster-internal IP.
  # Choosing this value makes the Service only reachable from within the cluster.
  type: ClusterIP
  ports:
    - name: app
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: greeting