apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-script: |
    CREATE DATABASE greeting;
    \c greeting;
    CREATE TABLE IF NOT EXISTS song (id serial PRIMARY KEY, name VARCHAR NOT NULL);