apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-script: |
    CREATE DATABASE greeting;
    \c greeting;
    CREATE TABLE greeting (id serial PRIMARY KEY, text VARCHAR UNIQUE NOT NULL);