apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-demo-file-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  # the volume can be mounted as read-write by a single Node
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
