apiVersion: v1
kind: Namespace
metadata:
  name: common

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: common
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-service
          image: waytodanny/k8s-101-user-service
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: common
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      #the port number which is exposed by the Kubernetes service. External services, or services within the same cluster, will communicate with this service on this port number.
      port: 8082
      #the port number on the pods where the actual service is running and requests will be sent. It is the port of your application on the actual pods targeted by the service.
      targetPort: 8082
      nodePort: 30002